import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/layout/Header'
import { Navigation } from '@/components/layout/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
	  	<header>
			<Header/>
		</header>
		<div className='flex flex-row'>
			<nav className='w-1/12 md:w-2/12'><Navigation/></nav>
			<main className='w-11/12 md:w-10/12 '>
			{children}
			</main>
		</div>
	  </body>
    </html>
  )
}
